Check in pipeline for failed tests

diff --git a/.github/workflows/config.yaml b/.github/workflows/config.yaml
--- a/.github/workflows/config.yaml
+++ b/.github/workflows/config.yaml
@@ -31,7 +31,9 @@ jobs:
         sudo apt-get install -y make
 
     - name: Run all standard simulation
-      run: make tests
+      run: |
+        make tests
+        [ ! -s results/failed_tests.txt ] || (echo "One or more tests failed" && exit 1)
 
     ## Steps for running programs
 
