Fix workflow

diff --git a/.github/workflows/config.yaml b/.github/workflows/config.yaml
--- a/.github/workflows/config.yaml
+++ b/.github/workflows/config.yaml
@@ -31,7 +31,8 @@ jobs:
         sudo apt-get install -y make
 
     - name: Run all standard simulation
-      run: make waveform.vcd
+      run: make tests
+        [ ! -s results/failed_tests.txt ] || (echo "One or more tests failed" && exit 1)
 
   c_to_sim:
     runs-on: ubuntu-latest
